# Generated by Django 5.1.4 on 2024-12-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Overdue', 'Overdue')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
