# Generated by Django 5.1.4 on 2024-12-09 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_members_confpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='website.members'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
