# Generated by Django 5.1.4 on 2024-12-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_tasks_owner_tasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
